version: '3'
services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: user-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/pg_isready -U postgres -d user-manager -h localhost || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  object-store:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    cap_drop:
      - NET_RAW
    volumes:
      - minio_data:/data
    entrypoint:
      - /bin/sh
      - -c
      - |
        # Start MinIO server in the background
        minio server --address ":9000" --console-address ":9001" /data &
        # Give the server a few seconds to start
        sleep 5
        # Set up MinIO Client (mc) to use the MinIO server
        mc alias set myminio http://localhost:9000 minioadmin minioadmin
        # Create the bucket
        mc mb myminio/user-manager || true
        # Keep the container running
        wait

  user-manager:
    build: .
    image: faisalagla/user-manager
    environment:
      ENV: dev
      DB_URL: jdbc:postgresql://db:5432/user-manager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      OBJECT_STORE_URL: http://object-store:9000
      OBJECT_STORE_ACCESS_KEY: minioadmin
      OBJECT_STORE_ACCESS_SECRET: minioadmin
      OBJECT_STORE_BUCKET_NAME: user-manager
      OBJECT_STORE_PROFILE_IMAGES_PREFIX: profile-images
      SERVER.PORT: 8090
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
      object-store:
        condition: service_started

volumes:
  minio_data:
    driver: local