version: '3'
services:
  user-db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: user-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/pg_isready -U postgres -d user-manager -h localhost || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/pg_isready -U keycloak -d keycloak -h localhost || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  object-store:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    cap_drop:
      - NET_RAW
    volumes:
      - minio_data:/data
    entrypoint:
      - /bin/sh
      - -c
      - |
        # Start MinIO server in the background
        minio server --address ":9000" --console-address ":9001" /data &
        # Give the server a few seconds to start
        sleep 5
        # Set up MinIO Client (mc) to use the MinIO server
        mc alias set myminio http://localhost:9000 minioadmin minioadmin
        # Create the bucket
        mc mb myminio/user-manager || true
        # Keep the container running
        wait

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false #dev
      KC_HOSTNAME_STRICT_HTTPS: false #dev
    ports:
      - '8081:8080'
    command: [ "start-dev" ]
    depends_on:
      keycloak-db:
        condition: service_healthy

  user-manager:
    build: .
    image: faisalagla/user-manager
    environment:
      ENV: dev
      DB_URL: jdbc:postgresql://user-db:5432/user-manager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      OBJECT_STORE_URL: http://object-store:9000
      OBJECT_STORE_ACCESS_KEY: minioadmin
      OBJECT_STORE_ACCESS_SECRET: minioadmin
      OBJECT_STORE_BUCKET_NAME: user-manager
      OBJECT_STORE_PROFILE_IMAGES_PREFIX: profile-images
      SERVER.PORT: 8090
    ports:
      - '8090:8090'
    depends_on:
      user-db:
        condition: service_healthy
      object-store:
        condition: service_started
      keycloak:
        condition: service_started

volumes:
  minio_data:
  user_db_data:
  keycloak_db_data: