version: '3'
services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: user-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - user-manager-network
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/pg_isready -U postgres -d user-manager -h localhost || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  object-store:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    cap_drop:
      - NET_RAW
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - user-manager-network

  user-manager:
    build: .
    image: faisalagla/user-manager
    environment:
      ENV: dev
      DB_URL: jdbc:postgresql://db:5432/user-manager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      OBJECT_STORE_URL: http://object-store:9000
      OBJECT_STORE_ACCESS_KEY: minioadmin
      OBJECT_STORE_ACCESS_SECRET: minioadmin
      OBJECT_STORE_BUCKET_NAME: user-manager
      OBJECT_STORE_MAX_RETRIES: 5
      OBJECT_STORE_RETRY_DELAY_MS: 2000
      SERVER.PORT: 8090
    ports:
      - "8090:8090"
    networks:
      - user-manager-network
    depends_on:
      db:
        condition: service_healthy
      object-store:
        condition: service_started

networks:
  user-manager-network:
    driver: "bridge"

volumes:
  minio_data:
    driver: local