spring:
  application:
    name: user-manager
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/user-manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
      contexts: ${ENV:prod}
      change-log: classpath:/db/liquibase/master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
          audiences: backend

springdoc:
  swagger-ui.enabled: ${ENABLE_SWAGGER:false}
  api-docs.enabled: ${ENABLE_SWAGGER:false}

server:
  port: ${SERVER.PORT:8090}

user-manager:
  env: ${ENV:prod}
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
  keycloak:
    realm: ${KEYCLOAK_REALM_NAME}
    client-id: ${KEYCLOAK_CLIENT_ID}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    auth-server-url: ${KEYCLOAK_SERVER_URL}
    user-redirect-url: ${KEYCLOAK_USER_REDIRECT_URL}
    audience: ${KEYCLOAK_AUDIENCE:roles}
  openapi:
    dev-url: ${OPENAPI_DEV_URL:http://localhost:8090}
    prod-url: ${OPENAPI_PROD_URL:http://localhost:8090}
  object-store:
    url: ${OBJECT_STORE_URL}
    access-key: ${OBJECT_STORE_ACCESS_KEY}
    access-secret: ${OBJECT_STORE_ACCESS_SECRET}
    bucket-name: ${OBJECT_STORE_BUCKET_NAME}
    profile-images-prefix: ${OBJECT_STORE_PROFILE_IMAGES_PREFIX:profile-images}
    allowed-image-types: ${ALLOWED_IMAGE_TYPES:image/jpeg,image/png}
    allowed-image-extensions: ${ALLOWED_IMAGE_EXTENSIONS:jpg,jpeg,png}
    max-file-size-mb: ${MAX_FILE_SIZE_MB:5}
