spring:
  application:
    name: user-manager
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/user-manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
      contexts: ${ENV:prod}
      change-log: classpath:/db/liquibase/master.yaml

user-manager:
  env: ${ENV:prod}
  openapi:
    dev-url: ${OPENAPI_DEV_URL:http://localhost:8080}
    prod-url: ${OPENAPI_PROD_URL:http://localhost:8080}