spring:
  application:
    name: user-manager
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/user-manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
      contexts: ${ENV:prod}
      change-log: classpath:/db/liquibase/master.yaml

server:
  port: ${SERVER.PORT:8090}

user-manager:
  env: ${ENV:prod}
  openapi:
    dev-url: ${OPENAPI_DEV_URL:http://localhost:8090}
    prod-url: ${OPENAPI_PROD_URL:http://localhost:8090}
  object-store:
    url: ${OBJECT_STORE_URL}
    access-key: ${OBJECT_STORE_ACCESS_KEY}
    access-secret: ${OBJECT_STORE_ACCESS_SECRET}
    bucket-name: ${OBJECT_STORE_BUCKET_NAME}
    max-retries: ${OBJECT_STORE_MAX_RETRIES:5}
    retry-delay-ms: ${OBJECT_STORE_RETRY_DELAY_MS:2000}